### ISSUE TITLE
Lässt sich nicht Kompilieren mit der angefügt Config...

### ISSUE THREAD

**Issue by o0shojo0o** [oderwat/Marlin#1]
Auszug der Log..

```
Arduino: 1.8.0 (Windows 10), Board: "Anet V1.0"
exit status 1
default argument given for parameter 2 of 'char* ftostr43sign(const float&, char)' [-fpermissive]
```

ultralcd.h Zeile 205
[Configuration.zip](https://github.com/oderwat/Marlin/files/678980/Configuration.zip)

Gruß

**Comment by oderwat** [comment]
Hmm. Bei mir geht es zu kompilieren:
[SKYNETV2.ino.sanguino.hex.zip](https://github.com/oderwat/Marlin/files/679030/SKYNETV2.ino.sanguino.hex.zip)

**Comment by o0shojo0o** [comment]
Wass nutzt Du für eine Arduino Version? 
Bzw. hast Du Anpassungen vorgenommen ?

**Comment by oderwat** [comment]
Ich denke ich weiss was es ist. Da waren noch Deklarationen doppelt. Komisch, dass er bei mir nicht gemeckert hat. Ziehe mal bitte das Archiv von hier neu und probiere es nochmal.

**Comment by o0shojo0o** [comment]
Yes, das war es! 
```
Der Sketch verwendet 110830 Bytes (84%) des Programmspeicherplatzes. Das Maximum sind 131072 Bytes.
Globale Variablen verwenden 4393 Bytes des dynamischen Speichers.
```
